### ISSUE TITLE
Got a syntax error

### ISSUE THREAD

**Issue by Kelier** [ssitu/ComfyUI_UltimateSDUpscale#10]
Total VRAM 16384 MB, total RAM 16384 MB
Set vram state to: SHARED
Device: mps
Using split optimization for cross attention
Traceback (most recent call last):
  File "/Users/cdown/dill/comyui/ComfyUI/nodes.py", line 1590, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/cdown/dill/comyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/Users/cdown/dill/comyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/nodes.py", line 5, in <module>
    from usdu_patch import usdu
  File "/Users/cdown/dill/comyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "/Users/cdown/dill/comyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "/Users/cdown/dill/comyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py", line 4, in <module>
    from modules import processing, shared, images, devices, scripts
  File "/Users/cdown/dill/comyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/modules/processing.py", line 69
    match p.uniform_tile_mode:
          ^
SyntaxError: invalid syntax

Cannot import /Users/cdown/dill/comyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale module for custom nodes: invalid syntax (processing.py, line 69)

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): /Users/cdown/dill/comyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale

Starting server

**Comment by Kelier** [comment]
> Total VRAM 16384 MB, total RAM 16384 MB Set vram state to: SHARED Device: mps Using split optimization for cross attention Traceback (most recent call last): File "/Users/cdown/dill/comyui/ComfyUI/nodes.py", line 1590, in load_custom_node module_spec.loader.exec_module(module) File "", line 850, in exec_module File "", line 228, in _call_with_frames_removed File "/Users/cdown/dill/comyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/**init**.py", line 23, in from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS File "/Users/cdown/dill/comyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/nodes.py", line 5, in from usdu_patch import usdu File "/Users/cdown/dill/comyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/usdu_patch.py", line 2, in from repositories import ultimate_upscale as usdu File "/Users/cdown/dill/comyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/**init**.py", line 14, in spec.loader.exec_module(ultimate_upscale) File "/Users/cdown/dill/comyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py", line 4, in from modules import processing, shared, images, devices, scripts File "/Users/cdown/dill/comyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/modules/processing.py", line 69 match p.uniform_tile_mode: ^ SyntaxError: invalid syntax
> 
> Cannot import /Users/cdown/dill/comyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale module for custom nodes: invalid syntax (processing.py, line 69)
> 
> Import times for custom nodes: 0.0 seconds (IMPORT FAILED): /Users/cdown/dill/comyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
> 
> Starting server

Can someone help me explain the cause of this problem

**Comment by ssitu** [comment]
You must have an old version of Python. I just changed some code so it should start working if you update.

**Comment by Kelier** [comment]
> You must have an old version of Python. I just changed some code so it should start working if you update.

thx a lot!
