### ISSUE TITLE
Issue with Comfyui

### ISSUE THREAD

**Issue by JoBo125** [ssitu/ComfyUI_UltimateSDUpscale#100]
I have an issue getting my UltimateSDUpscale to work from the Comfyui manager. Every time I try to download it says:

"UltimateSDUpscale install failed: Bad Request"

Causing it not to install and when I try to fix it on the manager nothing changes. I am still able to use the "HD Ultimate SD Upscale" node but none of the others and if I try to use someone else's workflow I am met with a red box. Hoping someone can help me out I am relatively new to Comfyui!

**Comment by HMBM47** [comment]
I just tried installing this using the manager as well, and it didn't work. 
Manual installation did. 
Just follow the Installation instructions on the first page of this hub. 
(Tip: Make sure to delete the existing "ComfyUI_UltimateSDUpscale" from your "ComfyUI/custom_nodes" folder before installing.

**Comment by Nainoor** [comment]
git config --system core.longpaths true

Try typing the above in your CMD as admin. Faced the same issue. @JoBo125

**Comment by david-peter-smith** [comment]
I am seeing the same issue as well on *nix.

Looking at the logs I was able to determine there is a missing module called `spandrel`

```
Traceback (most recent call last):
  File "/REDACTED/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/REDACTED/ComfyUI/comfy_extras/nodes_upscale_model.py", line 3, in <module>
    from spandrel import ModelLoader, ImageModelDescriptor
ModuleNotFoundError: No module named 'spandrel'
```

So In the virual environment I did a quick `pip install spandrel`

restarted the server and refreshed the nodes and it is working. My guess is the module was just missing in the node requirements, etc.

Hope this helps someone else or the dev updating the patch.

**Comment by dawkinsd93** [comment]
I'm currently getting the same issue and when i'm trying to git clone the repo. I've done the above recommendations including installing 'spandrel' and setting the git config long paths to true, but still no joy. Here's the error:

```
remote: Enumerating objects: 323, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (11/11), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 1605 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
fatal: clone of 'https://github.com/Coyote-A/ultimate-upscale-for-automatic1111' into submodule path 
```

**Comment by MadnNolimit** [comment]
I used this: git clone https://github.com/ssitu/ComfyUI_UltimateSDUpscale --recursive

But it might have some issue if path is too long:  
fatal: '$GIT_DIR' too big
fatal: remote helper 'https' aborted session

Use this command with a shorter path and move the folder to: \ComfyUI_windows_portable\ComfyUI\custom_nodes

Hope this helps
