### ISSUE TITLE
Error while running with flux1.dev !!! Exception during processing !!! not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by twistmachine** [ssitu/ComfyUI_UltimateSDUpscale#107]
I receive the error bellow when i run my workflow with this node, thanks for your help :

Python 3.12.5
Canva size: 1024x1024
Image size: 1024x1024
Scale factor: 1
Tile size: 512x512
Tiles amount: 4
Grid: 2x2
Redraw enabled: True
Seams fix mode: NONE
!!! Exception during processing !!! not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "C:\Users\rviau\ComfyUI\execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rviau\ComfyUI\execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rviau\ComfyUI\execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\rviau\ComfyUI\execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rviau\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 151, in upscale
    processed = script.run(p=self.sdprocessing, _=None, tile_width=self.tile_width, tile_height=self.tile_height,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rviau\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 565, in run
    upscaler.process()
  File "C:\Users\rviau\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 138, in process
    self.image = self.redraw.start(self.p, self.image, self.rows, self.cols)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rviau\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 245, in start
    return self.linear_process(p, image, rows, cols)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rviau\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 180, in linear_process
    processed = processing.process_images(p)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rviau\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\modules\processing.py", line 166, in process_images
    negative_cropped = crop_cond(p.negative, crop_region, p.init_size, init_image.size, tile_size)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rviau\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\utils.py", line 452, in crop_cond
    for emb, x in cond:
        ^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by PaoPao6190** [comment]
我也遇到了同样的问题，请问解决了吗？怎么解决呢？
