### ISSUE TITLE
Import Failed with the latest UlimateSDUpscale

### ISSUE THREAD

**Issue by masslevel** [ssitu/ComfyUI_UltimateSDUpscale#15]
I just did a clean clone of the latest version and when starting ComfyUI it throws an `Import Failed`.

Reverting to an older build of UltimateSDUpscale (used a version installed before 20230727) did fix the problem and it works correctly on the latest ComfyUI build.

```
Traceback (most recent call last):
  File "f:\ai\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ai\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ai\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 5, in <module>
    from usdu_patch import usdu
  File "F:\ai\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "F:\ai\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ai\\tools\\sd\\builds\\cui-work\\ComfyUI\\custom_nodes\\ComfyUI_UltimateSDUpscale\\repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py'

Cannot import F:\ai\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: [Errno 2] No such file or directory: 'F:\\ai\\tools\\sd\\builds\\cui-work\\ComfyUI\\custom_nodes\\ComfyUI_UltimateSDUpscale\\repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): F:\ai\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
```

**Comment by ssitu** [comment]
Can you check if there are any files in `F:\\ai\\ComfyUI\\custom_nodes\\ComfyUI_UltimateSDUpscale\\repositories`?

**Comment by Topzie** [comment]
I have the same and yes there are files in repositories

**Comment by ssitu** [comment]
> I have the same and yes there are files in repositories
> _pycache_ folder, ultimte_sd_upscale folder and _init_.py

Do you have the file that it says doesn’t exist? 

ComfyUI\\custom_nodes\\ComfyUI_UltimateSDUpscale\\repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py

**Comment by masslevel** [comment]
I'm sorry for the late reply, @ssitu 

There's no error when cloning the repo. And when you launch ComfyUI:

```
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ai\\ComfyUI\\custom_nodes\\ComfyUI_UltimateSDUpscale\\repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py'

Cannot import F:\ai\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: [Errno 2] No such file or directory: 'F:\\ai\\ComfyUI\\custom_nodes\\ComfyUI_UltimateSDUpscale\\repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): F:\ai\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
```

The folder `F:\\ai\\ComfyUI\\custom_nodes\\ComfyUI_UltimateSDUpscale\\repositories/` is empty after a fresh clone.

I cloned other node packages on this setup and they work. So I guess it has nothing to do with my setup.

**Comment by Topzie** [comment]
ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories/ultimate_sd_upscale/scripts/ is missing, so no scripts at all

To be clear, first I tried to update with the Manager, when that didn’t work I deleted the directory and did a git clone.
Results the  same as masslevel.

**Comment by Topzie** [comment]
Yes, I copied the command. Windows 11.

**Comment by ssitu** [comment]
@Topzie Try using the linked pull request, we'll see if the inconsistent path separators are causing the issue.

@masslevel Since you are missing files in the repositories folder, I believe it might be because you left out the `--recursive` option out of the git clone command. If not, then you could clone https://github.com/Coyote-A/ultimate-upscale-for-automatic1111 into the folder, and rename the folder to `ultimate_sd_upscale` so that the path `\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py` exists.

**Comment by Topzie** [comment]
Still doesn't work

Cannot import C:\Users\AI\Desktop\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: cannot import name 'pil_to_tensor' from 'utils' (C:\Users\AI\Desktop\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\utils.py)

**Comment by ssitu** [comment]
Oh that's a different error, it's a name conflict from the other custom node that you have installed. I'll have it fixed in a moment.

**Comment by rethink-studios** [comment]
two places?

script
https://github.com/melMass/comfy_mtb

paper
https://github.com/google-research/frame-interpolation

**Comment by ssitu** [comment]
I found that it is https://github.com/Fannovel16/ComfyUI-Frame-Interpolation. I installed it and it looks like the linked pull request resolves the conflict. Once I get some confirmation from @Topzie I'll merge the changes.

**Comment by ssitu** [comment]
I’ll merge the changes.

As for @masslevel, I believe you just missed the —recursive flag for the git clone.
The command should be as it says in the readme: git clone https://github.com/ssitu/ComfyUI_UltimateSDUpscale —recursive
