### ISSUE TITLE
Error when using with Conditioning (set area) + Conditioning (combine)

### ISSUE THREAD

**Issue by ParthGandhi** [ssitu/ComfyUI_UltimateSDUpscale#39]
```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/ubuntu/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/ubuntu/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/nodes.py", line 124, in upscale
    processed = script.run(p=sdprocessing, _=None, tile_width=tile_width, tile_height=tile_height,
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py", line 553, in run
    upscaler.process()
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py", line 136, in process
    self.image = self.redraw.start(self.p, self.image, self.rows, self.cols)
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py", line 243, in start
    return self.linear_process(p, image, rows, cols)
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py", line 178, in linear_process
    processed = processing.process_images(p)
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/modules/processing.py", line 110, in process_images
    positive_cropped = crop_cond(p.positive, crop_region, p.init_size, init_image.size, tile_size)
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/utils.py", line 457, in crop_cond
    crop_area(cond_dict, region, init_size, canvas_size, tile_size, w_pad, h_pad)
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/utils.py", line 391, in crop_area
    h, w, y, x = cond_dict["area"]
ValueError: too many values to unpack (expected 4)
```

If this is not expected I can give a reproducible example.

**Comment by ssitu** [comment]
It's probably just because of my outdated code. I'll update it eventually.
