### ISSUE TITLE
[Feature request] change "Canva size" to be divisible by 8

### ISSUE THREAD

**Issue by fractal-fumbler** [ssitu/ComfyUI_UltimateSDUpscale#4]
hello :)
thanks for your work :)

started to use new node "Ultimate SD Upscale (No upscale)". And encountering problems with picture resolution if it not divisible by 64.
Problem is that node is making picture bigger when sampling it.

For example, image is 968x1600 and node making it 1024x1600, because 968 isn't   divisible by 64

```
Canva size: 1024x1600                                                                                                   
Image size: 968x1600                                                                                                    
Scale factor: 1                                                                                                         
Tile size: 968x1600                                                                                                     
Tiles amount: 2                                                                                                         
Grid: 1x2                                                                                                               
Redraw enabled: True                                                                                                    
Seams fix mode: HALF_TILE 
```
but for "Ultimate SD Upscale (No upscale)". Canva size: 968x1600 :)     

is it possible to change Canva size behaviour to be divisible by 8?

**Comment by ssitu** [comment]
See if the latest commit works for you.

**Comment by fractal-fumbler** [comment]
it's working!

but if **seam fix mode** set to every possible option besides 'None' it giving error `TypeError: new_setup_seams_fix() missing 2 required positional arguments: 'width' and 'height'`
<details> <summary>Screenshot</summary>

![image](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/80472908/3f2a33b8-0e7b-4b91-a78b-251df26cafac)

</details>

```python
Canva size: 536x536                                                                                                     
Image size: 536x536                                                                                                     
Scale factor: 1                                                                                                         
Tile size: 536x536                                                                                                      
Tiles amount: 1                                                                                                         
Grid: 1x1                                                                                                               
Redraw enabled: True                                                                                                    
Seams fix mode: BAND_PASS                                                                                               
100%|███████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.62it/s]
!!! Exception during processing !!!                                                                                     
Traceback (most recent call last):                                                                                      
  File "/tmp/ComfyUI/execution.py", line 141, in recursive_execute                                                      
    output_data, output_ui = get_output_data(obj, input_data_all)                                                       
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                       
  File "/tmp/ComfyUI/execution.py", line 75, in get_output_data                                                         
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)                         
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                         
  File "/tmp/ComfyUI/execution.py", line 68, in map_node_over_list                                                      
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))                                                 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                    File "/tmp/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/nodes.py", line 161, in upscale                             
    processed = script.run(p=sdprocessing, _=None, tile_width=tile_width, tile_height=tile_height,                      
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                        File "/tmp/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py
", line 463, in run                                                                                                     
    upscaler.process()                                                                                                  
  File "/tmp/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py
", line 142, in process                                                                                                 
    self.image = self.seams_fix.start(self.p, self.image, self.rows, self.cols)                                         
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                         
  File "/tmp/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale/scripts/ultimate-upscale.p$
", line 407, in start                                                                                                   
    return self.band_pass_process(p, image, rows, cols)                                                                 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                 
  File "/tmp/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py
", line 353, in band_pass_process                                                                                       
    self.init_draw(p)                                                                                                   
TypeError: new_setup_seams_fix() missing 2 required positional arguments: 'width' and 'height'
```

**Comment by ssitu** [comment]
Hopefully it's fixed now.

**Comment by fractal-fumbler** [comment]
new error appeared
tested both with "Ultimate SD Upscale (No upscale)" and "Ultimate SD Upscale"

```python
Error occurred when executing UltimateSDUpscale:

new_setup_redraw() takes 2 positional arguments but 4 were given

  File "/tmp/ComfyUI/execution.py", line 141, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/nodes.py", line 121, in upscale
    processed = script.run(p=sdprocessing, _=None, tile_width=tile_width, tile_height=tile_height,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py", line 463, in run
    upscaler.process()
  File "/tmp/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py", line 135, in process
    self.image = self.redraw.start(self.p, self.image, self.rows, self.cols)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py", line 242, in start
    return self.linear_process(p, image, rows, cols)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py", line 169, in linear_process
    mask, draw = self.init_draw(p, image.width, image.height)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ssitu** [comment]
I changed the wrong bit of code, should be working now.

**Comment by fractal-fumbler** [comment]
Canva size working for me :fireworks: 

```
Canva size: 1600x968
Image size: 1600x968
Scale factor: 1
Tile size: 1600x968
Tiles amount: 1
```

**Comment by fractal-fumbler** [comment]
thanks a lot!

**Comment by ssitu** [comment]
No problem, I appreciate the suggestions!
