### ISSUE TITLE
TypeError while generating images with batch > 1

### ISSUE THREAD

**Issue by fractal-fumbler** [ssitu/ComfyUI_UltimateSDUpscale#5]
Hello :)

Tried to generate more than 1 picture at same time (batch = 2 or 4) with "Ultimate SD Upscale (No upscale)" getting error `TypeError: Cannot handle this data type: (1, 1, 1112, 3), |u1`

<details> <summary>detailed log</summary>

```python
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 3089, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
                    ~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: ((1, 1, 1112, 3), '|u1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/ComfyUI/execution.py", line 141, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/nodes.py", line 156, in upscale
    tensor_to_pil(upscaled_image), model, positive, negative, vae,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/utils.py", line 14, in tensor_to_pil
    img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8).squeeze())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 3092, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 1112, 3), |u1
```
</details>

**Comment by ssitu** [comment]
What exactly do you mean by batch? Is it the batch setting in vanilla ComfyUI?

**Comment by fractal-fumbler** [comment]
sorry, by batch size i meant "Empty latent image" node
![image](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/80472908/760d6721-7c2f-4ccc-bae5-92c8f45981c4)

**Comment by ssitu** [comment]
The latest commit should do the trick.

**Comment by fractal-fumbler** [comment]
haha, just came home to see your comment about tricks :D

tested and trick is happening with both nodes 

thanks a lot for your great magic! :)
