### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mayjack0312** [ssitu/ComfyUI_UltimateSDUpscale#54]
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 5, in <module>
    from usdu_patch import usdu
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 4, in <module>
    from modules import processing, shared, images, devices, scripts
ImportError: cannot import name 'images' from 'modules' (D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: cannot import name 'images' from 'modules' (D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)

**Comment by ssitu** [comment]
> i removed comfyui-reactor-node in custom nodes and now work. some conflict with this custom nodes.

Is this a recent conflict? Were the two compatible before?

**Comment by mayjack0312** [comment]
> i removed comfyui-reactor-node in custom nodes and now work. some conflict with this custom nodes.

Fantastic, all plugins are working properly, and no errors have been found so far.
