### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by offmybach** [ssitu/ComfyUI_UltimateSDUpscale#55]
I have tried to install via cmd in custom nodes, the manager and via link in manager. The file is in folder as if installed but won't load in any workflow. always red. failed to install and try fix doesn't work. what next? I need for 2 workflows badly. Please help!

**Comment by ssitu** [comment]
What errors are displayed in the terminal relating to this node?

**Comment by PabloMontero** [comment]
Same here.

I'm trying to install setting up this:
https://perilli.com/ai/comfyui/#download

![Uploading Screenshot 2024-02-02 at 11.34.18.png…]()

**Comment by GOATGAMER07** [comment]
solution below:

put ultimate-upscale.py in exact location which i provided location below

".....\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py"

**Comment by offmybach** [comment]
I have it there and no go for me.

D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py

**Comment by offmybach** [comment]
Here's error:
s' (unknown location)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 5, in <module>
    from usdu_patch import usdu
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 4, in <module>
    from modules import processing, shared, images, devices, scripts
ImportError: cannot import name 'images' from 'modules' (D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)

Cannot import D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: cannot import name 'images' from 'modules' (D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)

**Comment by PabloMontero** [comment]
I've seen that SD Ultimate Upscale comes into conflict with Reactor Pack. Try to disable Reactor and try.

**Comment by offmybach** [comment]
that won't install either LOL

**Comment by shiccup** [comment]
uninstalling reactor does fix it lol @offmybach neither of mine were importing maybe they don't work together or something.

**Comment by offmybach** [comment]
I tried adding the a1111 py file also but..... also reactor isn't loading and looks to be in direct conflict
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 5, in <module>
    from usdu_patch import usdu
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 4, in <module>
    from modules import processing, shared, images, devices, scripts
ImportError: cannot import name 'images' from 'modules' (D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)

Cannot import D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: cannot import name 'images' from 'modules' (D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)

**Comment by offmybach** [comment]
Can we get some help here? Seems like your node is used in every workflow I chose and am lost without it.

**Comment by offmybach** [comment]
> uninstalling reactor does fix it lol @offmybach neither of mine were importing maybe they don't work together or something.

very interesting

**Comment by offmybach** [comment]
> > uninstalling reactor does fix it lol @offmybach neither of mine were importing maybe they don't work together or something.
> 
> very interesting

I just did same and it works!  Somehow the 2 developers need to make these 2 play nice together.

**Comment by ssitu** [comment]
That's strange, I can't seem to reproduce the conflict. What other custom nodes do you have installed?

**Comment by Latentnaut** [comment]
With AP Workflow I found this issue. Note it was with v7, I couldn't try v8 yet.

https://perilli.com/ai/comfyui/
