### ISSUE TITLE
'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by zwbpds** [ssitu/ComfyUI_UltimateSDUpscale#63]
Error occurred when executing UltimateSDUpscale:

'NoneType' object has no attribute 'shape'

File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 125, in upscale
processed = script.run(p=sdprocessing, _=None, tile_width=tile_width, tile_height=tile_height,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 553, in run
upscaler.process()
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 136, in process
self.image = self.redraw.start(self.p, self.image, self.rows, self.cols)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 243, in start
return self.linear_process(p, image, rows, cols)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 178, in linear_process
processed = processing.process_images(p)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\modules\processing.py", line 122, in process_images
(samples,) = common_ksampler(p.model, p.seed, p.steps, p.cfg, p.sampler_name,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1325, in common_ksampler
samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-StableSR\nodes.py", line 69, in hook_sample
return original_sample(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
return original_sample(*args, **kwargs) # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 248, in motion_sample
return orig_comfy_sample(model, noise, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 100, in sample
samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 712, in sample
return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 602, in sample
positive = encode_model_conds(model.extra_conds, positive, noise, device, "positive", latent_image=latent_image, denoise_mask=denoise_mask, seed=seed)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 498, in encode_model_conds
out = model_function(**params)
^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\comfyUI\ComfyUI_windows_portable\ComfyUI\comfy\model_base.py", line 117, in extra_conds
if len(denoise_mask.shape) == len(noise.shape):
^^^^^^^^^^^^^^^^^^

**Comment by Lady-vamp** [comment]
Same issue, did you find a solution?

**Comment by BigUncle** [comment]
Try this.It may help.
https://github.com/ssitu/ComfyUI_UltimateSDUpscale/issues/62#issuecomment-1984923872

**Comment by zwbpds** [comment]
> Same issue, did you find a solution?

I currently don’t know what the real cause of the error is, but after I changed the checkpoint, this error has not appeared again. I'm guessing that the checkpoint I originally used may have a corrupted file, or it may be incompatible with my amplified workflow.

**Comment by sophyvathanak** [comment]
> > Same issue, did you find a solution?
> 
> I currently don’t know what the real cause of the error is, but after I changed the checkpoint, this error has not appeared again. I'm guessing that the checkpoint I originally used may have a corrupted file, or it may be incompatible with my amplified workflow.

What checkpoint you are using to make it normal?

**Comment by worthy7** [comment]
I also have this issue, it's something to do with using other stuff on the model path before reaching the SD Upscaler node.
If I connect a model directly, it works. If I have things like IP Adapter etc in the model flow, it doesn't.

**Comment by yachiyo96411** [comment]
I have the same issue
How can I resolve this?

**Comment by thijsi123** [comment]
Same issue:

```
22:34:24.562 [Info] Sent Comfy backend direct prompt requested to backend #0 (from user local)
22:34:58.244 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
22:34:58.245 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 349, in execute
22:34:58.245 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
22:34:58.246 [Warning] [ComfyUI-0/STDERR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.246 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 224, in get_output_data
22:34:58.246 [Warning] [ComfyUI-0/STDERR]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
22:34:58.247 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.247 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\comfyui-lora-manager\py\metadata_collector\metadata_hook.py", line 63, in map_node_over_list_with_metadata
22:34:58.247 [Warning] [ComfyUI-0/STDERR]     results = original_map_node_over_list(obj, input_data_all, func, allow_interrupt, execution_block_cb, pre_execute_cb)
22:34:58.248 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.248 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\comfyui-lora-manager\py\metadata_collector\metadata_hook.py", line 63, in map_node_over_list_with_metadata
22:34:58.248 [Warning] [ComfyUI-0/STDERR]     results = original_map_node_over_list(obj, input_data_all, func, allow_interrupt, execution_block_cb, pre_execute_cb)
22:34:58.249 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.249 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 196, in _map_node_over_list
22:34:58.249 [Warning] [ComfyUI-0/STDERR]     process_inputs(input_dict, i)
22:34:58.250 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 185, in process_inputs
22:34:58.250 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**inputs))
22:34:58.251 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.251 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 153, in upscale
22:34:58.251 [Warning] [ComfyUI-0/STDERR]     processed = script.run(p=sdprocessing, _=None, tile_width=self.tile_width, tile_height=self.tile_height,
22:34:58.252 [Warning] [ComfyUI-0/STDERR]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.252 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 565, in run
22:34:58.252 [Warning] [ComfyUI-0/STDERR]     upscaler.process()
22:34:58.253 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 138, in process
22:34:58.253 [Warning] [ComfyUI-0/STDERR]     self.image = self.redraw.start(self.p, self.image, self.rows, self.cols)
22:34:58.253 [Warning] [ComfyUI-0/STDERR]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.254 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 247, in start
22:34:58.254 [Warning] [ComfyUI-0/STDERR]     return self.chess_process(p, image, rows, cols)
22:34:58.254 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.255 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 217, in chess_process
22:34:58.255 [Warning] [ComfyUI-0/STDERR]     processed = processing.process_images(p)
22:34:58.255 [Warning] [ComfyUI-0/STDERR]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.256 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\modules\processing.py", line 230, in process_images
22:34:58.256 [Warning] [ComfyUI-0/STDERR]     samples = sample(p.model, p.seed, p.steps, p.cfg, p.sampler_name, p.scheduler, positive_cropped,
22:34:58.257 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.257 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\modules\processing.py", line 162, in sample
22:34:58.258 [Warning] [ComfyUI-0/STDERR]     (samples,) = common_ksampler(model, seed, steps, cfg, sampler_name,
22:34:58.258 [Warning] [ComfyUI-0/STDERR]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.259 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 1485, in common_ksampler
22:34:58.259 [Warning] [ComfyUI-0/STDERR]     samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
22:34:58.259 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.260 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Apt_Preset\NodeBasic\C_model.py", line 517, in sample
22:34:58.260 [Warning] [ComfyUI-0/STDERR]     return original_sample(*args, **kwargs)
22:34:58.260 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.261 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\sample.py", line 45, in sample
22:34:58.261 [Warning] [ComfyUI-0/STDERR]     samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
22:34:58.262 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.262 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 1139, in sample
22:34:58.262 [Warning] [ComfyUI-0/STDERR]     return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
22:34:58.263 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.264 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 1029, in sample
22:34:58.264 [Warning] [ComfyUI-0/STDERR]     return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
22:34:58.265 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.265 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 1014, in sample
22:34:58.265 [Warning] [ComfyUI-0/STDERR]     output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
22:34:58.266 [Warning] [ComfyUI-0/STDERR]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.266 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\patcher_extension.py", line 111, in execute
22:34:58.267 [Warning] [ComfyUI-0/STDERR]     return self.original(*args, **kwargs)
22:34:58.267 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.268 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 982, in outer_sample
22:34:58.269 [Warning] [ComfyUI-0/STDERR]     output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
22:34:58.269 [Warning] [ComfyUI-0/STDERR]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.270 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 965, in inner_sample
22:34:58.270 [Warning] [ComfyUI-0/STDERR]     samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
22:34:58.271 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.272 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\patcher_extension.py", line 111, in execute
22:34:58.272 [Warning] [ComfyUI-0/STDERR]     return self.original(*args, **kwargs)
22:34:58.273 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.274 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 744, in sample
22:34:58.274 [Warning] [ComfyUI-0/STDERR]     samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
22:34:58.275 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.275 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
22:34:58.276 [Warning] [ComfyUI-0/STDERR]     return func(*args, **kwargs)
22:34:58.276 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^
22:34:58.276 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\k_diffusion\sampling.py", line 181, in sample_euler_ancestral
22:34:58.277 [Warning] [ComfyUI-0/STDERR]     denoised = model(x, sigmas[i] * s_in, **extra_args)
22:34:58.277 [Warning] [ComfyUI-0/STDERR]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.278 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 396, in __call__
22:34:58.278 [Warning] [ComfyUI-0/STDERR]     out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
22:34:58.279 [Warning] [ComfyUI-0/STDERR]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.279 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 945, in __call__
22:34:58.280 [Warning] [ComfyUI-0/STDERR]     return self.predict_noise(*args, **kwargs)
22:34:58.280 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.281 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 948, in predict_noise
22:34:58.281 [Warning] [ComfyUI-0/STDERR]     return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
22:34:58.282 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.283 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 376, in sampling_function
22:34:58.283 [Warning] [ComfyUI-0/STDERR]     out = calc_cond_batch(model, conds, x, timestep, model_options)
22:34:58.284 [Warning] [ComfyUI-0/STDERR]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.284 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 206, in calc_cond_batch
22:34:58.285 [Warning] [ComfyUI-0/STDERR]     return executor.execute(model, conds, x_in, timestep, model_options)
22:34:58.285 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.286 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\patcher_extension.py", line 111, in execute
22:34:58.286 [Warning] [ComfyUI-0/STDERR]     return self.original(*args, **kwargs)
22:34:58.287 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.288 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 320, in _calc_cond_batch
22:34:58.288 [Warning] [ComfyUI-0/STDERR]     c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond), transformer_options)
22:34:58.288 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.289 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\controlnet.py", line 273, in get_control
22:34:58.289 [Warning] [ComfyUI-0/STDERR]     control = self.control_model(x=x_noisy.to(dtype), hint=self.cond_hint, timesteps=timestep.to(dtype), context=context.to(dtype), **extra)
22:34:58.290 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.290 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
22:34:58.290 [Warning] [ComfyUI-0/STDERR]     return self._call_impl(*args, **kwargs)
22:34:58.291 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.291 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
22:34:58.291 [Warning] [ComfyUI-0/STDERR]     return forward_call(*args, **kwargs)
22:34:58.292 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:34:58.292 [Warning] [ComfyUI-0/STDERR]   File "G:\AI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\cldm\cldm.py", line 416, in forward
22:34:58.292 [Warning] [ComfyUI-0/STDERR]     assert y.shape[0] == x.shape[0]
22:34:58.293 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^
22:34:58.293 [Warning] [ComfyUI-0/STDERR] AttributeError: 'NoneType' object has no attribute 'shape'
22:34:58.294 [Warning] [ComfyUI-0/STDERR]

```

**Comment by thijsi123** [comment]
Is it because I'm using sdxl?
