### ISSUE TITLE
ImportError: attempted relative import beyond top-level package

### ISSUE THREAD

**Issue by cs7p** [ssitu/ComfyUI_UltimateSDUpscale#69]
**I've tried reinstalling the node and deleting the Reactor node, and that didn't fix the issue.**

Traceback (most recent call last):
  File "/mnt/workspace/ComfyUI/nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/__init__.py", line 32, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/nodes.py", line 5, in <module>
    from usdu_patch import usdu
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py", line 4, in <module>
    from modules import processing, shared, images, devices, scripts
  File "/opt/conda/lib/python3.10/site-packages/MultiScaleDeformableAttention-1.0-py3.10-linux-x86_64.egg/modules/__init__.py", line 12, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "/opt/conda/lib/python3.10/site-packages/MultiScaleDeformableAttention-1.0-py3.10-linux-x86_64.egg/modules/ms_deform_attn.py", line 21, in <module>
    from ..functions import MSDeformAttnFunction
ImportError: attempted relative import beyond top-level package

Cannot import /mnt/workspace/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale module for custom nodes: attempted relative import beyond top-level package

**Comment by cs7p** [comment]
Fixed the issue after adding __ init__. py in the modules directory

**Comment by ssitu** [comment]
> Fixed the issue after adding __ init__. py in the modules directory

So you just fixed it by adding an `__init__.py` to the `modules` folder?

**Comment by cs7p** [comment]
Yes, there may be a modules module in the runtime environment, and usdu_patch. py will prioritize importing the modules from the runtime environment. 

Therefore, I tried adding an empty content of __ init__. py to the modules folder, and the problem was resolved. 

I am not familiar with Python, this is just a speculation about the mechanism of importing dependency packages in Python, but it has indeed solved my problem. 

Thank you for your reply!

### My operating environment:
**Platform: Linux
**Python version: 3.10.13 (main, Sep 11 2023, 13:21:10) [GCC 11.2.0]
**Python executable:/opt/conda/bin/Python
**Log path:/mnt/workspace/ConfyUI/Confyui.log

Total VRAM 22732 MB, total RAM 30149 MB
Xforms version: 0.0.23+cu118
Set vram state to: NORMAL_VRAM
Device: cuda: 0 NVIDIA A10: cudaMallocAsync
VAE dtype: torch. bfloat16
Using pytorch cross attention
NumExpr defaulting to 8 threads

**Comment by ssitu** [comment]
I'll add it in case it fixes it for others, thank you for your find.
