### ISSUE TITLE
更新内核后，无法加载节点了

### ISSUE THREAD

**Issue by qiulinj666** [ssitu/ComfyUI_UltimateSDUpscale#78]
更新到最的管理器后，已经无法识别和加载这个节点了，管理器里显示是红色的

**Comment by Linka0512** [comment]
me to

Traceback (most recent call last):
  File "G:\ComfyUI-aki\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI-aki\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 32, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "G:\ComfyUI-aki\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 6, in <module>
    from usdu_patch import usdu
  File "G:\ComfyUI-aki\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "G:\ComfyUI-aki\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "G:\ComfyUI-aki\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 6, in <module>
    from modules.processing import Processed
ImportError: cannot import name 'Processed' from 'modules.processing' (G:\ComfyUI-aki\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\comfyui-reactor-node\modules\processing.py)

Cannot import G:\ComfyUI-aki\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: cannot import name 'Processed' from 'modules.processing' (G:\ComfyUI-aki\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\comfyui-reactor-node\modules\processing.py)

**Comment by LianTianNo1** [comment]
me to

When loading the graph, the following node types were not found:
UltimateSDUpscale[ 🔗](https://github.com/ssitu/ComfyUI_UltimateSDUpscale)
Nodes that have failed to load will show as red on the graph.

**Comment by qiulinj666** [comment]
![1716039261285](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/168464044/28527726-9bb6-46fb-8d5e-a5968f72cdd9)
like this

**Comment by LianTianNo1** [comment]
I suddenly became like this two hours ago.

**Comment by ghl245213993** [comment]
这是为啥呀

**Comment by lihuazhang** [comment]
+1

**Comment by ghl245213993** [comment]
Reactor卸载掉就正常了

**Comment by TamakoT** [comment]
原来都有这个问题呀，我还在这儿想半天为啥，python不是很懂，我研究了一下大概好像是本来应该导入ComfyUI_UltimateSDUpscale/modules下的processing.py，但是它导入找的是reactor的processing.py，不是它应该找的python文件，所以找不到对应的Processed这个东西，最后也不知道怎么解决，不懂为什么更新了下comfyui版本会出这样的问题

**Comment by qiulinj666** [comment]
> Reactor卸载掉就正常了

这样可以解决吗？会对其他插件有影响吗？

**Comment by qiulinj666** [comment]
> 原来都有这个问题呀，我还在这儿想半天为啥，python不是很懂，我研究了一下大概好像是本来应该导入ComfyUI_UltimateSDUpscale/modules下的processing.py，但是它导入找的是reactor的processing.py，不是它应该找的python文件，所以找不到对应的Processed这个东西，最后也不知道怎么解决，不懂为什么更新了下comfyui版本会出这样的问题

已经解决了，把原先的插件删掉，在comfyui/扩展插件文件夹下运行cmd,再运行这段git clone https://github.com/ssitu/ComfyUI_UltimateSDUpscale --recursive，最主要就是后面的--racursive,直接下载是缺少脚本文件夹的。

**Comment by TamakoT** [comment]
> > 原来都有这个问题呀，我还在这儿想半天为啥，python不是很懂，我研究了一下大概好像是本来应该导入ComfyUI_UltimateSDUpscale/modules下的processing.py，但是它导入找的是reactor的processing.py，不是它应该找的python文件，所以找不到对应的Processed这个东西，最后也不知道怎么解决，不懂为什么更新了下comfyui版本会出这样的问题
> 
> 已经解决了，把原先的插件删掉，在comfyui/扩展插件文件夹下运行cmd,再运行这段git clone [ssitu/ComfyUI_UltimateSDUpscale](https://github.com/ssitu/ComfyUI_UltimateSDUpscale) --recursive，最主要就是后面的--racursive,直接下载是缺少脚本文件夹的。

解决问题了，谢谢

**Comment by quanzaiyu** [comment]
> git clone https://github.com/ssitu/ComfyUI_UltimateSDUpscale --recursive

问题解决了，谢谢

**Comment by alenhrp** [comment]
问题解决了

> > git clone https://github.com/ssitu/ComfyUI_UltimateSDUpscale --recursive
> 
> 问题解决了，谢谢

**Comment by Sdreamtale** [comment]
我也遇到这个问题了，但是连不上服务器，用了VPN了还是不行，到了下载脚本阶段就提示不能链接
