### ISSUE TITLE
cumfyui importing fail

### ISSUE THREAD

**Issue by raochinmay6** [ssitu/ComfyUI_UltimateSDUpscale#84]
I try so much but comfy ui manager show error while importing this node

**Comment by raochinmay6** [comment]
![Screenshot (211)](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/160831464/ee252050-fb7d-47a7-8c33-2ef7d6adc7dd)
![Screenshot (212)](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/160831464/9cfd7bba-1cc1-4b0c-b414-030dd3f2891f)

see this images
![Uploading Screenshot (212).png…]()

**Comment by ssitu** [comment]
What error does the terminal give you?

**Comment by raochinmay6** [comment]
Node import failed

**Comment by raochinmay6** [comment]
Node not loading

**Comment by ssitu** [comment]
Can I see the full log, or if you know where to look, the part of the log that has the traceback of the import failed error?

**Comment by raochinmay6** [comment]
Where to look?

**Comment by ssitu** [comment]
It should look similar to the first comment in this other post:
https://github.com/ssitu/ComfyUI_UltimateSDUpscale/issues/69

**Comment by raochinmay6** [comment]
Ok when I reach home I will send it here

**Comment by tafkadec** [comment]
I'm having the same issue. Did you find a fix?

**Comment by raochinmay6** [comment]
Just post log file here he will find it for you

**Comment by prudernan** [comment]
i have the same problem, Apparently my problem is related to the spandrel file, thank you for helping me, my log file:


Microsoft Windows [Versión 10.0.22631.3593]
(c) Microsoft Corporation. Todos los derechos reservados.

C:\Users\prude\pinokio\api\comfyui.git\app>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && C:\Users\prude\pinokio\api\comfyui.git\app\env\Scripts\activate C:\Users\prude\pinokio\api\comfyui.git\app\env && python main.py --disable-xformers
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-31 00:15:48.815606
** Platform: Windows
** Python version: 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
** Python executable: C:\Users\prude\pinokio\api\comfyui.git\app\env\Scripts\python.exe
** Log path: C:\Users\prude\pinokio\api\comfyui.git\app\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\rgthree-comfy
   0.5 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Manager

Total VRAM 24575 MB, total RAM 32644 MB
pytorch version: 2.2.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Traceback (most recent call last):
  File "C:\Users\prude\pinokio\api\comfyui.git\app\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\prude\pinokio\api\comfyui.git\app\comfy_extras\nodes_upscale_model.py", line 3, in <module>
    from spandrel import ModelLoader, ImageModelDescriptor
ModuleNotFoundError: No module named 'spandrel'

Cannot import C:\Users\prude\pinokio\api\comfyui.git\app\comfy_extras\nodes_upscale_model.py module for custom nodes: No module named 'spandrel'
[AnimateDiffEvo] - ERROR - No motion models found. Please download one and place in: ['C:\\Users\\prude\\pinokio\\api\\comfyui.git\\app\\custom_nodes\\ComfyUI-AnimateDiff-Evolved\\models', 'C:\\Users\\prude\\pinokio\\api\\comfyui.git\\app\\models\\animatediff_models']
### ComfyUI-FaceSwap: Check dependencies
### ComfyUI-FaceSwap: Check basic models
A new version of Albumentations is available: 1.4.8 (you have 1.4.7). Upgrade using: pip install --upgrade albumentations
### Loading: ComfyUI-Impact-Pack (V5.7)
### ComfyUI-Impact-Pack: Reinstall dependencies (several dependencies are missing.)
### ComfyUI-Impact-Pack: Check dependencies
### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['C:\\Users\\prude\\pinokio\\api\\comfyui.git\\app\\env\\Scripts\\python.exe', 'install.py'] in 'C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
req_path: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
req_path: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
### ComfyUI-Impact-Pack: Check basic models
Traceback (most recent call last):
  File "C:\Users\prude\pinokio\api\comfyui.git\app\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 74, in <module>
    import impact.impact_server  # to load server api
  File "C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 12, in <module>
    import impact.core as core
  File "C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 15, in <module>
    import comfy_extras.nodes_upscale_model as model_upscale
  File "C:\Users\prude\pinokio\api\comfyui.git\app\comfy_extras\nodes_upscale_model.py", line 3, in <module>
    from spandrel import ModelLoader, ImageModelDescriptor
ModuleNotFoundError: No module named 'spandrel'

Cannot import C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: No module named 'spandrel'
### Loading: ComfyUI-Inspire-Pack (V0.71)
Total VRAM 24575 MB, total RAM 32644 MB
pytorch version: 2.2.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
### Loading: ComfyUI-Manager (V2.35.1)
### ComfyUI Revision: 2217 [71ec5b14] | Released on '2024-05-29'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
Imported node: DT_Flatten_Colors
Imported node: DT_FontText[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
Imported node: DT_GenerateNoise
Imported node: DT_Glitch_This
Imported node: DT_Hue_Rotation
Imported node: DT_Load_Picture_Index
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Imported node: DT_PILGram
Imported node: DT_Pixel_Sort
Imported node: DT_Play_Sound_At_Execution
Imported node: DT_PromptGen
Imported node: DT_Solid_Color
Imported node: DT_Swap_Color_Mode
Imported node: DT_Flatten_Colors
Imported node: DT_FontText
Imported node: DT_GenerateNoise
Imported node: DT_Glitch_This
Imported node: DT_Hue_Rotation
Imported node: DT_Load_Picture_Index
Imported node: DT_PILGram
Imported node: DT_Pixel_Sort
Imported node: DT_Play_Sound_At_Execution
Imported node: DT_PromptGen
Imported node: DT_Solid_Color
Imported node: DT_Swap_Color_Mode
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
[05/31/24 00:16:10] WARNING  Your inference package version 0.9.13 is out of date! Please upgrade to version 0.11.2 of inference for the latest features and bug fixes by running `pip install --upgrade inference`.                                                                                             __init__.py:35
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Traceback (most recent call last):
  File "C:\Users\prude\pinokio\api\comfyui.git\app\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 32, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 10, in <module>
    from modules.upscaler import UpscalerData
  File "C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_UltimateSDUpscale\modules\upscaler.py", line 3, in <module>
    from comfy_extras.nodes_upscale_model import ImageUpscaleWithModel
  File "C:\Users\prude\pinokio\api\comfyui.git\app\comfy_extras\nodes_upscale_model.py", line 3, in <module>
    from spandrel import ModelLoader, ImageModelDescriptor
**ModuleNotFoundError: No module named 'spandrel'**

**Cannot import C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: No module named 'spandrel'**
[comfy_mtb] | INFO -> loaded 76 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.

[rgthree] Loaded 39 extraordinary nodes.
[rgthree] Will use rgthree's optimized recursive execution.


Import times for custom nodes:
   0.0 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\SD-Latent-Upscaler
   0.0 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-SAI_API
   0.0 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_InstantID
   0.0 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_essentials
   0.1 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\rgthree-comfy
   0.1 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\comfyui_controlnet_aux
   **0.1 seconds (IMPORT FAILED): C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_UltimateSDUpscale**
   0.1 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Inspire-Pack
   0.2 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-VideoHelperSuite
   0.4 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Upscaler-Tensorrt
   0.4 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Manager
   1.6 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Vextra-Nodes
   1.8 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\comfy_mtb
   2.4 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-FaceSwap
   3.6 seconds: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-YoloWorld-EfficientSAM
   8.2 seconds (IMPORT FAILED): C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Impact-Pack

WARNING: some comfy_extras/ nodes did not import correctly. This may be because they are missing some dependencies.

IMPORT FAILED: nodes_upscale_model.py

This issue might be caused by new missing dependencies added the last time you updated ComfyUI.
Please do a: pip install -r requirements.txt

Starting server

To see the GUI go to: http://127.0.0.1:8188

[Start proxy] Local Sharing http://127.0.0.1:8188
Proxy Started {"target":"http://127.0.0.1:8188","proxy":"http://192.168.3.28:42421"}
FETCH DATA from: C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'UpscalerTensorrt' node.
Traceback (most recent call last):
  File "C:\Users\prude\pinokio\api\comfyui.git\app\server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "C:\Users\prude\pinokio\api\comfyui.git\app\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "C:\Users\prude\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Upscaler-Tensorrt\__init__.py", line 16, in INPUT_TYPES
    "engine": (os.listdir(ENGINE_DIR),),
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'C:\\Users\\prude\\pinokio\\api\\comfyui.git\\app\\models\\tensorrt\\upscaler'

FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json [DONE]

**Comment by gmf1982** [comment]
My Solution：Go to the venv\Lib\site-packages of A1111 webui and copy the two folders "spandrel and spandrel-0.1.6.dist-info" to the venv of comfyui.

**Comment by razv23** [comment]
> My Solution：Go to the venv\Lib\site-packages of A1111 webui and copy the two folders "spandrel and spandrel-0.1.6.dist-info" to the venv of comfyui.

I've used that method, it works for me as well. Thanks for suggesting it.

**Comment by ArnorWing** [comment]
This solution worked!! Thanks @gmf1982

**Comment by freshlesh3** [comment]
I dont have a1111 installed.  Is there an alternate way to resolve this?

**Comment by gmf1982** [comment]
> 我没有安装 a1111。还有其他方法可以解决这个问题吗？

After activating the virtual environment, pip install spandrel
