### ISSUE TITLE
Unable to load after last update

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [ssitu/ComfyUI_UltimateSDUpscale#92]
I updated after commit f55e3d870e232117f90db514327721c7b0fd81f6
```
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 32, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 141
    <<<<<<< Updated upstream
    ^^
SyntaxError: invalid syntax

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: invalid syntax (nodes.py, line 141)
```

**Comment by GalaxyTimeMachine** [comment]
I thought this may be a local problem, so I deleted the directory and cloned it again. I now get this error:

```
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 32, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 6, in <module>
    from usdu_patch import usdu
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_UltimateSDUpscale\\repositories\\ultimate_sd_upscale\\scripts\\ultimate-upscale.py'

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: [Errno 2] No such file or directory: 'F:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_UltimateSDUpscale\\repositories\\ultimate_sd_upscale\\scripts\\ultimate-upscale.py'
```

**Comment by GalaxyTimeMachine** [comment]
I missed the "--recursive" on the clone, so it works now. Sorry for wasting your time!
