### ISSUE TITLE
No such file or directory: ultimate-upscale.py

### ISSUE THREAD

**Issue by SyncBAND** [ssitu/ComfyUI_UltimateSDUpscale#95]
Hi. I'm getting the following error after installing the package

```Traceback (most recent call last):
  File "/app/ComfyUI/nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/__init__.py", line 32, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/app/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/nodes.py", line 6, in <module>
    from usdu_patch import usdu
  File "/app/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "/app/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/app/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py'```

**Comment by ssitu** [comment]
Make sure you add --recursive to your git clone command. Since you already have it installed then you'll want to try running `git submodule update --init --recursive` in the repo's folder instead.

**Comment by dfghsderftgerdf** [comment]
The above step did not work?

> Make sure you add --recursive to your git clone command. Since you already have it installed then you'll want to try running `git submodule update --init --recursive` in the repo's folder instead.

**Comment by thinkcoin** [comment]
Perhaps the /app/ in the start is the problem, looks like it's pointing always to the same place all the way, even if it's installed in a different place in the setup.

**Comment by MrXsc** [comment]
you could also clone this submodule: [ultimate-upscale-for-automatic1111](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111) manually,  just like clone a normal repository.
